### ISSUE TITLE
lx  ly dmax

### ISSUE THREAD

**Issue by jinchunwang** [limuyang0404/generate-fold-and-fault#9]
你好！
        我想问一下伍新明老师的论文中有关lx,ly,dmax是如何定义计算的？在代码中的取值范围该如何设置，是不是与断层的倾角和走向有关联？
        期待您的回复！
![Uploading 屏幕截图 2023-08-23 095721.png…]()

**Comment by limuyang0404** [comment]
关于断层位移场的长短轴和最大位移量我建议最好根据设置的数据体大小自适应调整，如果一定要设置在固定范围较小的参数能够有效避免数据体畸变。
之前我跟伍老师沟通过一次，他说他是先确定了位移后的各点再由位移场反推，下来我会尝试一下，有后续会跟你分享。
期待你的回复



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月23日 09:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [limuyang0404/generate-fold-and-fault] lx ly dmax (Issue #9) |

你好！
我想问一下伍新明老师的论文中有关lx,ly,dmax是如何定义计算的？在代码中的取值范围该如何设置，是不是与断层的倾角和走向有关联？
期待您的回复！
